x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 100m
      max-file: "3"
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  sui-node:
    build:
      context: ./sui
      dockerfile: Dockerfile.binary
      args:
        - DOCKER_TAG=${DOCKER_TAG}
    image: sui-node:${DOCKER_TAG:-local}
    pull_policy: never
    user: sui
    stop_grace_period: 5m
    restart: unless-stopped
    environment:
      - NETWORK=${NETWORK}
      - EXTRAS=${EXTRAS}
      - RPC_PORT=${RPC_PORT:-9000}
      - P2P_PORT=${P2P_PORT:-8084}
      - SNAPSHOT_EPOCH=${SNAPSHOT_EPOCH:-}
      - SNAPSHOT_PARALLEL_DOWNLOADS=${SNAPSHOT_PARALLEL_DOWNLOADS:-50}
      - SNAPSHOT_MAX_RETRIES=${SNAPSHOT_MAX_RETRIES:-3}
      - NUM_EPOCHS_TO_RETAIN=${NUM_EPOCHS_TO_RETAIN:-0}
      - NUM_EPOCHS_TO_RETAIN_FOR_CHECKPOINTS=${NUM_EPOCHS_TO_RETAIN_FOR_CHECKPOINTS:-2}
      - RPC_ENABLE_INDEXING=${RPC_ENABLE_INDEXING:-false}
      - RPC_ENABLE_INDEX_PROCESSING=${RPC_ENABLE_INDEX_PROCESSING:-false}
      - ARCHIVE_INGESTION_URL=${ARCHIVE_INGESTION_URL:-}
      - ARCHIVE_CONCURRENCY=${ARCHIVE_CONCURRENCY:-5}
      - ARCHIVE_AWS_KEY_FILE=${ARCHIVE_AWS_KEY_FILE:-}
      - ARCHIVE_AWS_SECRET_FILE=${ARCHIVE_AWS_SECRET_FILE:-}
      - AWS_REQUEST_PAYER=${AWS_REQUEST_PAYER:-true}
    <<: *logging
    entrypoint:
      - docker-entrypoint.sh
      - sui-node
      - --config-path
      - /opt/sui/config/node.yml
    ports:
      - ${P2P_PORT:-8084}:${P2P_PORT:-8084}/udp
    volumes:
      - sui-data:/opt/sui
    labels:
        - traefik.enable=true
        - traefik.http.routers.${RPC_HOST}.service=${RPC_HOST}
        - traefik.http.routers.${RPC_HOST}.entrypoints=websecure
        - traefik.http.routers.${RPC_HOST}.rule=Host(`${RPC_HOST}.${DOMAIN}`)
        - traefik.http.routers.${RPC_HOST}.tls.certresolver=letsencrypt
        - traefik.http.routers.${RPC_HOST}lb.service=${RPC_HOST}
        - traefik.http.routers.${RPC_HOST}lb.entrypoints=websecure
        - traefik.http.routers.${RPC_HOST}lb.rule=Host(`${RPC_LB}.${DOMAIN}`)
        - traefik.http.routers.${RPC_HOST}lb.tls.certresolver=letsencrypt
        - traefik.http.services.${RPC_HOST}.loadbalancer.server.port=${RPC_PORT}
        - metrics.scrape=true
        - metrics.path=/metrics
        - metrics.port=9184
        - metrics.instance=sui
        - metrics.network=${NETWORK}

volumes:
  sui-data:
